# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.imaging-service-request-ig
canonical: http://hl7.org/fhir/uv/imaging-service-request-ig
version: 0.1.0
name: FHIRImagingServiceRequestIG
title: FHIR Imaging ServiceRequest Profile IG
status: draft
publisher: 
  - name: HL7 International / Imaging Integration
  - url: http://www.hl7.org/Special/committees/imagemgt/index.cfm
contact:
  - name: HL7 International / Imaging Integration
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/imagemgt/index.cfm
  - name: Jonathan Whitby
    telecom:
      - system: email
        value: jonathan.whitby@mi.medical.canon
  - name: Brian Bialecki
    telecom:
      - system: email
        value: bbialecki@acr.org
  - name: Bas van den Heuvel
    telecom:
      - system: email
        value: bas.van.den.heuvel@philips.com
description: Profile FHIR ServiceRequest and related resources to fulfill the image ordering use cases.
jurisdiction: "http://unstats.un.org/unsd/methods/m49/m49.htm#001"
license: CC0-1.0
fhirVersion: 5.0.0
copyrightYear: 2021+
releaseLabel: ci-build
dependencies:
  fhir.dicom:
    uri: http://fhir.org/packages/fhir.dicom
    version: 2024.2.20240331
parameters:
  show-inherited-invariants: false
  usage-stats-opt-out: true
  apply-contact: true
  apply-context: true
  apply-copyright: true
  apply-jurisdiction: true
  apply-license: true
  apply-publisher: true
  apply-version: true

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: ii

pages:
  index.md:
    title: Home
    generation: markdown
  background.md:
    title: Background
    generation: markdown
#   architecture.md:
#     title: Architecture
#     generation: markdown
#   mapping.md:
#     title: Mapping
#     generation: markdown

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Contents: toc.html
  Background: background.html
#  Architecture: architecture.html
#  Mapping: mapping.html
  Artifact Index: artifacts.html
